title: Blog Sistemas Empotrados
description: Blog para las pr√°cticas de Sistemas Empotrados y de tiempo real
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
